//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.0
//     Template : Microsoft.Bond.Rules.dll#Rules_Bond_CSharp.tt
//     File     : csharp_services.cs
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::BondTransport;
using global::BondNetlibTransport;
using global::Microsoft.Bond;
using global::System;
using global::System.Collections.Generic;

namespace Multimedia
{
} // namespace Multimedia
namespace ObjectStore
{
} // namespace ObjectStore
namespace Microsoft
{
namespace ObjectStore
{
namespace QueueService
{
namespace Multi
{
} // namespace Multi
} // namespace QueueService
namespace Schema
{
} // namespace Schema
} // namespace ObjectStore
} // namespace Microsoft
namespace H_
{
} // namespace H_
namespace IndexService
{
} // namespace IndexService
namespace DeepLearning
{
} // namespace DeepLearning
namespace A1
{
namespace Replication
{
} // namespace Replication
} // namespace A1
namespace ObjectStoreDP
{
} // namespace ObjectStoreDP
namespace ANNFileStore
{
} // namespace ANNFileStore
